spring:
  datasource:
    url: jdbc:mysql://localhost/application
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    changelog: classpath:db/db.changelog-master.xml